#!/usr/bin/env python3
"""LuaSTG CoreCLR API 生成器。

从 LuaSTG/LuaSTG/CLRBinding/API/*.hpp 中的 X-macro 列表生成 C# 侧的
UnmanagedAPI 函数指针表声明（CSharp/LuaSTG/LuaSTG.Core/Generated/UnmanagedAPI.g.cs）。

用法：
    python tool/clr-api-generator/generate.py

修改 CLRBinding/API/ 下的模块列表后必须重新运行本脚本。
"""

import re
import sys
import pathlib

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
API_DIR = REPO_ROOT / "LuaSTG" / "LuaSTG" / "CLRBinding" / "API"
API_LIST = API_DIR / "APIList.hpp"
OUTPUT = REPO_ROOT / "CSharp" / "LuaSTG" / "LuaSTG.Core" / "Generated" / "UnmanagedAPI.g.cs"

# C++ 类型 -> C# 类型 映射（API 边界只允许这些类型）
TYPE_MAP = {
    "void": "void",
    "bool": "byte",  # C++ bool（1 字节）；C# 侧统一用 byte 表达，避免封送歧义
    "int8_t": "sbyte",
    "uint8_t": "byte",
    "int16_t": "short",
    "uint16_t": "ushort",
    "int32_t": "int",
    "uint32_t": "uint",
    "int64_t": "long",
    "uint64_t": "ulong",
    "float": "float",
    "double": "double",
    "size_t": "nuint",
    "intptr_t": "nint",
    "uintptr_t": "nuint",
    "const char*": "byte*",       # UTF-8 字符串，由调用方保证生命周期
    "char*": "byte*",
    "const char16_t*": "char*",   # UTF-16 字符串
    "char16_t*": "char*",
    "const void*": "void*",
    "void*": "void*",
    "const uint32_t*": "uint*",
    "uint32_t*": "uint*",
    "const double*": "double*",
    "double*": "double*",
    "const int32_t*": "int*",
    "int32_t*": "int*",
    "const uint8_t*": "byte*",
    "uint8_t*": "byte*",
}

API_RE = re.compile(
    r"^\s*DECLARE_CLR_API\s*\(\s*([^,()]+?)\s*,\s*(\w+)\s*,\s*\((.*?)\)\s*\)\s*$",
    re.MULTILINE,
)
INCLUDE_RE = re.compile(r'^\s*#\s*include\s+"(CLRBinding/API/[^"]+)"', re.MULTILINE)

HEADER = """\
// <auto-generated>
// 此文件由 tool/clr-api-generator/generate.py 生成，请勿手动修改。
// 源定义：LuaSTG/LuaSTG/CLRBinding/API/*.hpp
// </auto-generated>

#nullable enable

using System.Runtime.InteropServices;

namespace LuaSTG.Core
{{
    /// <summary>
    /// 引擎（C++）提供的非托管 API 函数指针表。
    /// 修改 CLRBinding/API/ 下的定义后需要重新运行生成器。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct UnmanagedAPI
    {{
        /// <summary>API 数量，用于与引擎侧一致性校验</summary>
        public uint UnmanagedApiCount;

{fields}

        /// <summary>C# 侧编译期已知的 API 数量</summary>
        public const int ExpectedApiCount = {count};
    }}
}}
"""


def strip_comments(text: str) -> str:
    text = re.sub(r"//[^\n]*", "", text)
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return text


def map_type(cpp_type: str, name: str, file: str, where: str) -> str:
    t = " ".join(cpp_type.split())
    if t not in TYPE_MAP:
        raise SystemExit(f"错误：{file}: 无法映射类型 '{cpp_type}'（{where} {name}），"
                         f"请在 {pathlib.Path(__file__).name} 的 TYPE_MAP 中添加映射")
    return TYPE_MAP[t]


def parse_api_line(line: str, file: str) -> tuple:
    m = API_RE.match(line)
    if not m:
        raise SystemExit(f"错误：{file}: 无法解析 API 声明：{line.strip()}")
    ret_cpp, name, params = m.group(1).strip(), m.group(2).strip(), m.group(3).strip()
    ret_cs = map_type(ret_cpp, name, file, "返回值")

    args_cs = []
    if params:
        # 参数之间不存在嵌套括号，直接按逗号切分
        for param in params.split(","):
            param = param.strip()
            if not param:
                continue
            parts = param.rsplit(None, 1)
            if len(parts) != 2:
                raise SystemExit(f"错误：{file}: 无法解析参数 '{param}'（{name}）")
            ptype, pname = parts
            args_cs.append((map_type(ptype, name, file, f"参数 {pname}"), pname))

    # 生成 delegate* unmanaged[Cdecl]<args, ret>
    arg_types = ", ".join(t for t, _ in args_cs)
    if arg_types:
        fptr = f"delegate* unmanaged[Cdecl]<{arg_types}, {ret_cs}>"
    else:
        fptr = f"delegate* unmanaged[Cdecl]<{ret_cs}>"
    return name, fptr


def main() -> int:
    # 收集模块文件（按 APIList.hpp 中的顺序）
    modules = []
    list_text = strip_comments(API_LIST.read_text(encoding="utf-8"))
    for inc in INCLUDE_RE.finditer(list_text):
        # include 路径相对于 LuaSTG/LuaSTG/
        modules.append(REPO_ROOT / "LuaSTG" / "LuaSTG" / inc.group(1))

    fields = []
    seen = set()
    for module in modules:
        text = strip_comments(module.read_text(encoding="utf-8"))
        for line in text.splitlines():
            if "DECLARE_CLR_API" not in line:
                continue
            name, fptr = parse_api_line(line, str(module))
            if name in seen:
                raise SystemExit(f"错误：API 名称重复：{name}（{module}）")
            seen.add(name)
            fields.append(f"        public {fptr} {name};")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        HEADER.format(fields="\n".join(fields), count=len(fields)),
        encoding="utf-8",
    )
    print(f"已生成 {OUTPUT}（{len(fields)} 个 API）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
